# Generated by Django 5.0.3 on 2024-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=11, verbose_name="手机号码")),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
            ],
            options={
                "verbose_name": "手机验证码表",
                "verbose_name_plural": "手机验证码表",
                "db_table": "verifcode",
            },
        ),
    ]
