# Generated by Django 3.2 on 2023-11-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addr',
            old_name='user_id',
            new_name='user',
        ),
    ]
