# Generated by Django 3.2 on 2024-03-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240326_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addr',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='addr',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='addr',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='area',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='area',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='area',
            name='update_time',
        ),
    ]
