# Generated by Django 5.0.3 on 2024-05-11 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collect",
            name="user",
            field=models.ForeignKey(
                help_text="用户ID",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户ID",
            ),
        ),
        migrations.AddField(
            model_name="detail",
            name="goods",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.goods",
                verbose_name="商品",
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="goods",
            field=models.ForeignKey(
                help_text="商品ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.goods",
                verbose_name="商品ID",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="group",
            field=models.ForeignKey(
                help_text="分类",
                max_length=20,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.goodsgroup",
                verbose_name="分类",
            ),
        ),
    ]
