# Generated by Django 3.2 on 2023-12-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goodsgroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsgroup',
            options={},
        ),
        migrations.AlterModelTable(
            name='goodsgroup',
            table=None,
        ),
    ]
