# Generated by Django 3.2 on 2023-12-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20231227_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsgroup',
            options={'verbose_name': '商品分类表', 'verbose_name_plural': '商品分类表'},
        ),
        migrations.AlterModelTable(
            name='goodsgroup',
            table='goods_group',
        ),
    ]
