# Generated by Django 3.2 on 2024-03-26 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20240326_1952'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20240326_2013'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addr',
            field=models.ForeignKey(default=1, help_text='地址ID', on_delete=django.db.models.deletion.DO_NOTHING, to='users.addr', verbose_name='地址ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.ForeignKey(help_text='商品ID', on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goods', verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='用户ID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
    ]
