# Generated by Django 3.2 on 2024-03-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20240326_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addr',
            field=models.CharField(help_text='收货地址', max_length=256, verbose_name='收货地址'),
        ),
    ]
