# Generated by Django 3.2 on 2024-03-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(blank=True, default=True, help_text='订单状态', verbose_name='订单状态'),
        ),
    ]
